---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-application
  labels:
    app: web-application
    release: prom
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      scrapeTimeout: 30s
      port: metrics
      path: /metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: web-application

