kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-svc
  labels:
    app: hello-svc
    workshop: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-svc
  template:
    metadata:
      labels:
        app: hello-svc
        workshop: workshop
    spec:
      containers:
        - name: hello-svc
          image: bashofmann/k8s-workshop-hello-svc:5.0.0
          ports:
            - containerPort: 3001
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 1
            periodSeconds: 1
            failureThreshold: 3
