image:
  tag: 1.0.0
  pullPolicy: Always

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: symfony-demo-<YOURNAME>.sflive.plgrnd.be
      paths:
        - /

  tls:
    - hosts:
      - symfony-demo-<YOURNAME>.sflive.plgrnd.be
